// Instale a extensão REST Client para efetuar os testes
// Teste da API REST de Pets, Clientes e Estadia

@basePetURL = https://trabalho-no-sql.vercel.app/api/pets
@baseUsuario = https://trabalho-no-sql.vercel.app/api/usuarios

@baseUsuarioTeste = http://localhost:3000/api/usuarios

@idPet = 680e782478d4b003262dedaf

@idEstadia = 680e776178d4b003262dedae

###
// GET - Lista todos os pets com filtros
GET {{basePetURL}}?cpfCliente=47192768812&especie=cachorro&porte=medio&idade_min=2&idade_max=8
Content-Type: application/json

###
// GET - Busca pet pelo ID
GET {{basePetURL}}/{{idPet}}
Content-Type: application/json

###
// POST - Cadastra novo pet
POST {{basePetURL}}
Content-Type: application/json

{
  "nome": "Pandora",
  "especie": "Cachorro",
  "raca": "Border Collie",
  "idade": 5,
  "sexo": "femea",
  "porte": "medio",
  "observacoes": "Muito brincalhona",
  "peso": 15,
  "cpfCliente": "47192768812",
  "nome_tutor": "Vanessa Capuano e Vitor Ruan"
}

###
// PUT - Atualiza dados de um pet
PUT {{basePetURL}}/{{idPet}}
Content-Type: application/json

{
  "nome": "Pandora",
  "especie": "Cachorro",
  "raca": "Vira-lata",
  "idade": 8,
  "sexo": "Macho",
  "porte": "medio",
  "observacoes": "Adora água",
  "peso": 8,
  "cpfCliente": "12345678900",
  "nome_tutor": "Vanessa Capuano"
}

###
// DELETE - Remove pet
DELETE {{basePetURL}}/{{idPet}}
Content-Type: application/json


###
// GET - Lista estadias (filtrar por CPF)
GET {{baseUsuarioTeste}}
Content-Type: application/json

###
// GET - Lista estadias por intervalo de datas
GET {{baseUsuarioTeste}}/682e5f5fb6a84a646d6a70be
Content-Type: application/json

###
// GET - Buscar estadia pelo ID
GET {{baseUsuarioTeste}}/6838cb5e89959c040d13b58f
Content-Type: application/json

###
// POST - Cadastrar nova estadia
# @prompt senha
POST {{baseUsuarioTeste}}
Content-Type: application/json

{
  "cpf":"47251787806",
  "nome": "Davy Oliveira Ribeiro",
  "email":"davy.oliv.ribeiro@gmail.com",
  "senha" : {{senha}}
}

###
// PUT - Atualizar estadia
# @prompt senha
PUT @{{baseUsuarioTeste}}/6838cb5e89959c040d13b58f
Content-Type: application/json

{
  "nome": "João",
  "cpf": "71248522001",
  "email": "teste@teste.com",
  "senha": {{{{senha}}}}
}

###
// DELETE - Remover estadia
DELETE {{baseUsuarioTeste}}/6838cb5e89959c040d13b58f
Content-Type: application/json
