// Instale a extensão REST Client para efetuar os testes
// Teste da API REST de Pets, Clientes e usuário

@basePetURL = http://localhost:3000/api/pets

@baseUsuario = http://localhost:3000/api/usuarios
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjg0NzY5MjNhOWMxOTY3YjIzYzNkOTEwIn0sImlhdCI6MTc0OTUxNjQ4MCwiZXhwIjoxNzQ5NTE2NDgwfQ.6j0AhnJEAmBjRfWP8Ktc_zqZAvAOKja1mc1pm9AN5rA

@idPet = 680e782478d4b003262dedaf

@idusuário = 680e776178d4b003262dedae

###
// GET - Lista todos os pets com filtros
GET {{basePetURL}}
Content-Type: application/json
accessToken: {{token}}

###
// GET - Busca pet pelo ID
GET {{basePetURL}}/{{idPet}}
Content-Type: application/json

###
// POST - Cadastra novo pet
POST {{basePetURL}}
Content-Type: application/json

{
  "nome": "Pandora",
  "especie": "Cachorro",
  "raca": "Border Collie",
  "idade": 5,
  "sexo": "femea",
  "porte": "medio",
  "observacoes": "Muito brincalhona",
  "peso": 15,
  "cpf": "47192768812"
}

###
// PUT - Atualiza dados de um pet
PUT {{basePetURL}}/
Content-Type: application/json

{
  "nome": "Pandora",
  "especie": "Cachorro",
  "raca": "Vira-lata",
  "idade": 8,
  "sexo": "Macho",
  "porte": "medio",
  "observacoes": "Adora água",
  "peso": 8,
  "cpf": "12345678900",
}

###
// DELETE - Remove pet
DELETE {{basePetURL}}/{{idPet}}
Content-Type: application/json


###
// GET - Lista usuarios (filtrar por CPF)
GET {{baseUsuario}}
Content-Type: application/json

###
// GET - Buscar usuário pelo ID
GET {{baseUsuario}}/68476119496d5d43f5f4dffc
Content-Type: application/json

###
// POST - Cadastrar nova usuário
# @prompt senha
POST {{baseUsuario}}
Content-Type: application/json

{
  "nome": "Joao",
  "cpf": "47251787806",
  "email": "joao@gmail.com",
  "senha": "{{senha}}"
}

###
// POST para o JEST - Cadastrar 
# @prompt senha
POST {{baseUsuario}}
Content-Type: application/json

{
  "nome": "Teste",
  "cpf": "47251787806",
  "email": "teste@exemplo.com",
  "senha": "{{senha}}"
}

###
// PUT - Atualizar usuário
# @prompt senha
PUT @{{baseUsuario}}/68476119496d5d43f5f4dffc
Content-Type: application/json

{
  "nome": "Joao",
  "cpf": "47251787806",
  "email": "joao@gmail.com",
  "senha": "{{senha}}"
}

###
// LOGIN - LOGAR

# @prompt senha
POST {{baseUsuario}}/login
Content-Type: application/json

{
  "email": "joao@gmail.com",
  "senha": "{{senha}}"
}

###
// DELETE - Remover usuário
DELETE {{baseUsuario}}/683224f82f71b833502a3e02
Content-Type: application/json
